# Rigshospitalet case exploratory data analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

df = pd.read_csv('data/Case Rigshospitalet.csv')

/var/folders/2q/fq4zt8r176583r4v4jy_hxgh0000gn/T/ipykernel_90530/2593110826.py:1: DtypeWarning: Columns (9,13,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/Case Rigshospitalet.csv')

In [5]:

df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4658066 entries, 0 to 4658065
Data columns (total 24 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   Patient ID                               object
 1   Patientkontakt ID                        int64
 2   Patient alder på kontaktstart tidspunkt  int64
 3   Kontakt startdato                        object
 4   Kontakt slutdato                         object
 5   Kontakttype                              object
 6   Indlæggelsesmåde                         object
 7   Patientkontakttype                       object
 8   Aktionsdiagnosekode                      object
 9   Bidiagnosekode                           object
 10  Behandlingsansvarlig Afdeling            object
 11  Kontakt varighed (timer)                 object
 12  Procedure-kode                           object
 13  Procedure-tillægskoder                   object
 14  Procedure udført                         object
 15  Behandlingskontakt ID                    object
 16  Besøgstype                               object
 17  Patient køn                              object
 18  Patient civilstand                       object
 19  Patient oprettet på Min SP (J/N)         object
 20  Patient land                             object
 21  Patient region                           object
 22  Patient postnummer                       object
 23  Patient kommune                          object
dtypes: int64(2), object(22)
memory usage: 852.9+ MB

In [6]:
df.head()

,Patient ID,Patientkontakt ID,Patient alder på kontaktstart tidspunkt,Kontakt startdato,Kontakt slutdato,Kontakttype,Indlæggelsesmåde,Patientkontakttype,Aktionsdiagnosekode,Bidiagnosekode,...,Procedure udført,Behandlingskontakt ID,Besøgstype,Patient køn,Patient civilstand,Patient oprettet på Min SP (J/N),Patient land,Patient region,Patient postnummer,Patient kommune
0,Z4115614,1301023075465,0,"2023-01-13 12:32:00,000","2023-01-13 13:02:00,000",Fysisk fremmøde,Planlagt,2 Ambulant,DZ001,NaN,...,"2023-01-13 12:32:00,000",176.794.528,OBST EFTERFØDSEL 30,Mand,Ugift,J,Danmark,Hovedstaden (84),2100,København
1,Z4115614,1301023121831,0,"2023-01-15 13:27:00,000","2023-01-15 13:57:00,000",Fysisk fremmøde,Planlagt,2 Ambulant,DZ001,NaN,...,"2023-01-15 13:27:00,000",177.035.032,OBST EFTERFØDSEL 30,Mand,Ugift,J,Danmark,Hovedstaden (84),2100,København
2,Z4119225,1301023357249,0,"2023-01-30 10:20:00,000","2023-01-30 10:50:00,000",Fysisk fremmøde,Planlagt,2 Ambulant,DZ001,NaN,...,"2023-01-30 10:20:00,000",178.269.449,OBST EFTERFØDSEL 30,Mand,Ugift,J,Danmark,Hovedstaden (84),2100,København
3,Z4127033,1301023443807,0,"2023-02-04 12:46:00,000","2023-02-04 13:16:00,000",Fysisk fremmøde,Planlagt,2 Ambulant,DZ001,NaN,...,"2023-02-04 12:46:00,000",178.703.583,OBST EFTERFØDSEL 30,Mand,Ugift,J,Danmark,Hovedstaden (84),2100,København
4,Z4127033,1301023443875,0,"2023-02-05 12:22:00,000","2023-02-05 12:52:00,000",Fysisk fremmøde,Planlagt,2 Ambulant,DZ001,NaN,...,"2023-02-05 12:22:00,000",178.703.779,OBST EFTERFØDSEL 30,Mand,Ugift,J,Danmark,Hovedstaden (84),2100,København